matrix:
  include:
    - os: linux
      language: android
      dist: trusty
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-28.0.3
          - android-28
          - sys-img-armeabi-v7a-google_apis-28
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
          sources:
            - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
          packages:
            - libstdc++6
            - fonts-droid
      before_install:
        - yes | sdkmanager --update
      before_script:
        - git clone -b master https://github.com/flutter/flutter.git
        - git checkout -b stable v1.5.4-hotfix.2
        - export PATH="$PATH:`pwd`/flutter/bin"
      script:
        - yes | flutter doctor --android-licenses
        - flutter doctor && flutter -v build apk

    - os: osx
      language: objective-c
      osx_image: xcode10.2
      before_script:
        - pip install six
        - brew update
        - brew uninstall --ignore-dependencies -f libimobiledevice
        - brew uninstall --ignore-dependencies -f usbmuxd
        - brew install --HEAD usbmuxd
        - brew unlink usbmuxd
        - brew link usbmuxd
        - brew install --HEAD libimobiledevice
        - brew install ideviceinstaller
        - git clone -b master https://github.com/flutter/flutter.git
        - git checkout -b stable v1.5.4-hotfix.2
        - export PATH="$PATH:`pwd`/flutter/bin"
      script:
        - flutter doctor && flutter -v build ios --no-codesign

cache:
  directories:
    - $HOME/.pub-cache
